---
- hosts: ubuntu
  remote_user: sysadmin
  become: yes
 
 

  tasks:

  - name: Mariadb server install
    apt:
      name: mariadb-server
      state: present
      update_cache: yes

  - name: Mariadb service enable and start
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Configure mariadb to listen on all interfaces
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: 'bind_address'
      line: bind_address = 0.0.0.0/0

  - name: Open mariadb ports
    ufw:
     rule: allow
     port: "3306"
     proto: tcp

#MYSQL Secure Installation
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - dbpassword.yml

  tasks:

  - name: Update MariaDB root password
    mysql_user:
      login_host: 192.168.56.20
      login_user: root
      login_password: ""    
      name: root
      host: "{{ item }}"
      password: "{{ rootpass }}"
    loop:
      - 127.0.0.1
      - localhost
      - 192.168.56.0/24
      

  - name: Delete anonymous user
    mysql_user:
      login_host: 192.168.56.20
      login_user: root
      login_password: "{{ rootpass }}"
      name: ""
      state: absent
  

  - name: Delete test database
    mysql_db:
      login_host: 192.168.56.20
      login_user: root
      login_password: "{{ rootpass }}"      
      name: test
      state: absent     

